# 570 Interim Deliverable 2

## MIP formulation

#### Input data:  
$$\begin{aligned}
\text{Section information:}
&& I & = \text{{all course sections}} \\
&& student & = \text{{predicted number of students who will register for each section}} \\
&& PS & = \text{{number of sessions for each section}}  \\
&& TS & = \text{{the timelength of each session in hours (e.g., 1.5, 2, 3)}}  \\
&& I_2 & = \text{{sections with 2 sessions a week (i.e., MW and TH)}} \\
\\
\text{Classroom information:}
&& J & = \text{{classrooms}} \\
&& seat & = \text{{number of seats in each classroom}}  \\
\\
\text{Day-time information:}
&& P & = \text{{day of week (i.e., M T W H F)}}  \\
&& T & = \text{{start time of a section}} \\
\end{aligned}$$

#### Decision variable:
Let the binary decision variable $X_{ijpt}$ denotes whether we assign course section $i$ to classroom $j$ at day $p$ starting at time $t$.

#### Objective and constraints:
Our goal is to maximize the capacity utilization rate. The linear program is thus:
$$\begin{aligned}
\text{maximize} && \sum_{i\in I}\sum_{j\in J}\sum_{p\in P}\sum_{t\in T}{X_{ijpt}\frac{student_i}{seat_j}} \\
\text{subject to:} \\
\
\text{No start time conflict for classes:} && X_{ijpt} + X_{(I-i)jpt} & \le 1 && \forall i \in I, j \in J, p \in P, t \in T\\
\\
\text{No class conflict when a class is in session:} && X_{ijpt} + X_{i'jp(t+c)}& \le 1 && \forall i,i' \in I; j \in J; p \in P; t \in T; c \in \{1,2,...,TS_i*2-1\}\\
\\
\text{All required sessions must be scheduled:} && \sum_{j\in J}\sum_{p\in P}\sum_{t\in T}{X_{ijpt}} & = PS_i && \forall i \in I\\
\\
\text{Number of students must not exceed total seats:} && X_{ijpt} * student_i & \le seat_j && \forall i \in I, j \in J, p \in P, t \in T \\
\\
\text{No class scheduled  to last beyond school time (i.e., 9.30PM):} && X_{ijpt'} & = 0 && \forall i \in I, j \in J, p \in P, t' \in \{T_{max}-(TS_i*2)+2,...,T_{max}\} \\
\\
\text{Binding clause for courses with 2 sessions (MW):} && X_{ij'M't} & = X_{ij'W't} && \forall i \in I_2, j \in J, t \in T\\
\text{Binding clause for courses with 2 sessions (TH):} && X_{ij'T't} & = X_{ij'H't} && \forall i \in I_2, j \in J, t \in T\\
\\
\text{No Friday class for courses with 2 sessions:} && X_{ij'F't} & = 0 && \forall i \in I_2, j \in J, t \in T \\
\end{aligned}$$

# Python Code

In [1]:
import gurobipy as grb
import pandas as pd
import numpy as np
import datetime
from datetime import time
from datetime import timedelta
import math
import random

# for the room capacity file i remove the first record because it is same as the 7th record and will make some error in next step
capacity=pd.read_excel("Marshall_Room_Capacity_Chart.xlsx")
capacity1=capacity
course_enrollment=pd.read_excel("Marshall_Course_Enrollment_1516_1617.xlsx") # for student prediction
#course=pd.read_excel("Marshall_Course_Enrollment_1516_1617_small.xlsx")
#section_info=pd.read_excel("section information.xlsx")

In [2]:
course_enrollment.head()

,Course,Course Prefix,Course Suffix,Department,First Begin Time,First Days,First End Time,First Instructor,First Instructor UID,First Room,...,Second Begin Time,Second Days,Second End Time,Second Instructor,Second Instructor UID,Second Room,Section,Session,Term,Title
0,ACCT-370,ACCT,370,ACCT,10:00:00,F,11:50:00,"Hopkins, Merle, W",3.783354e+09,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14029,1,20153,External Financial Reporting Issues
1,ACCT-370,ACCT,370,ACCT,08:00:00,MW,09:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14025,1,20153,External Financial Reporting Issues
2,ACCT-370,ACCT,370,ACCT,10:00:00,MW,11:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14026,1,20153,External Financial Reporting Issues
3,ACCT-370,ACCT,370,ACCT,12:00:00,MW,13:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14027,1,20153,External Financial Reporting Issues
4,ACCT-371,ACCT,371,ACCT,10:00:00,F,11:50:00,NaN,NaN,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14044,1,20153,Introduction to Accounting Systems

## Extra data from original dataset

In [5]:
# choose 20153 term as sample
data=course_enrollment.loc[course_enrollment.loc[:,"Term"]==20153,("Course","Section","First Days","First Begin Time","First End Time","First Room","First Instructor")]
data.columns=["Course","Section","FirstDays","FirstBeginTime","FirstEndTime","FirstRoom","FirstInstructor"]
# we only use those M/T/W/H/F/MW/TH
data=data[(data.FirstDays=="M")|(data.FirstDays=="T")|(data.FirstDays=="W")|(data.FirstDays=="H")|(data.FirstDays=="F")|(data.FirstDays=="MW")|(data.FirstDays=="TH")]
data=data[(data.FirstRoom!="ONLINE")&(data.FirstRoom!="DEN@Viterbi")]
# remove the record that have nan in first begintime
data=data[(data.FirstBeginTime==data.FirstBeginTime)|(data.FirstEndTime==data.FirstEndTime)]
# remove the record that have nan in professor
data=data[data.FirstInstructor==data.FirstInstructor]
data=data.loc[:,("Course","Section","FirstDays","FirstBeginTime","FirstEndTime","FirstInstructor")]

In [6]:
# timelength
timelength=[]
for i in data.index:
    #print i
    #print data.loc[i,:]
    #print data.loc[i,:]
    time1=data.loc[i,"FirstEndTime"]
    #print type(time1)
    time2=data.loc[i,"FirstBeginTime"]
    minutediff=((time1.hour*60+time1.minute)-(time2.hour*60+time2.minute)+10)
    halfhour=minutediff/30
    if minutediff%30>0:
        halfhour+=1
    timelength.append(halfhour)

In [7]:
# pattern
pattern=[]
for i in data.index:
    day=data.loc[i,"FirstDays"]
    if (day=="M") or (day=="T") or (day=="W") or (day=="H") or (day=="F"):
        #print day
        pattern.append(1)
    elif (day=="MW") or (day=="TH"):
        #print day
        pattern.append(2)

### move the prediction of reg students from build variables to here

In [8]:
# students' registeration prediction
student={}
for i in data["Section"]:
    sum1=sum(course_enrollment.loc[course_enrollment.loc[:,"Section"]==i,"Reg Count"])
    len1=len(course_enrollment.loc[course_enrollment.loc[:,"Section"]==i,"Reg Count"])
    student[i]=round(sum1/len1)
    #print student[i]
#print student.values()
#student=pd.Series(i for i in student)

Use the "section_info=section_info[section_info.timelength<=2]" below to control the size of dataset (change value of 2), i only tried small one

### add reg count column to section_info

In [7]:
# build section_info table
section_info=pd.DataFrame({"course":data["Course"],"section":data["Section"],"pattern":pattern,
                           "timelength":timelength,"FirstInstructor":data["FirstInstructor"],
                           "Reg Count":student.values()})
print section_info.head()
# we only use those timelength less than 1.5 hours
section_info=section_info[section_info.timelength<=4]
# build table of professor and sections
Prof=section_info["FirstInstructor"].unique()
professor={}
for i in Prof:
    professor[i]=section_info.loc[section_info.loc[:,"FirstInstructor"]==i,"section"]
print max(section_info["timelength"])
print len(section_info)
#print section_info.index
# for change the index, do not delete 
section_info.index=range(len(section_info))
# get how many sessions we have in this sechedule
numofsections=sum(section_info["pattern"])
numofprof=len(Prof)
section_info.index

          FirstInstructor  Reg Count    course  pattern  section  timelength
0       Hopkins, Merle, W       40.0  ACCT-370        1    14029           4
1       Hopkins, Merle, W       42.0  ACCT-370        2    14025           4
2       Hopkins, Merle, W       53.0  ACCT-370        2    14026           4
3       Hopkins, Merle, W       48.0  ACCT-370        2    14027           4
5  Porter, Leslie, Robert       47.0  ACCT-371        2    14040           4
4
427

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            417, 418, 419, 420, 421, 422, 423, 424, 425, 426],
           dtype='int64', length=427)

### change the size of sample dataset

In [8]:
# only keep those classes with reg count less than 150, so ll105 can meet the need of seats
section_info=section_info.loc[section_info.loc[:,"Reg Count"]<=149,:]
section_info=section_info.reset_index(drop=True)
# randomly choose 100 sections
random.seed(1)
indexofsection=random.sample(section_info.index,100)
section_info=section_info.iloc[indexofsection,:]
#reset dataframe's index 
section_info=section_info.reset_index(drop=True)

In [9]:
# get the subset of prof
Prof=section_info["FirstInstructor"].unique()
professor={}
for i in Prof:
    professor[i]=section_info.loc[section_info.loc[:,"FirstInstructor"]==i,"section"]
numofsections=sum(section_info["pattern"])
numofprof=len(Prof)
print numofsections
print numofprof

170
74

In [10]:
capacity

         Room  Size
0      ACC201    48
1      ACC205    36
2      ACC236    39
3      ACC303    46
4     ACC306B    16
5      ACC310    54
6      ACC312    20
7      BRI202    42
8     BRI202A    34
9        BRI5    42
10       BRI8    36
11    HOH EDI   269
12       HOH1    73
13       HOH2    73
14     HOH506    16
15     HOH706    16
16  JFF LL101    48
17  JFF LL102    48
18  JFF LL103    48
19  JFF LL105   149
20  JFF LL125   101
21     JFF233    60
22     JFF236    60
23     JFF239    48
24     JFF240    48
25     JFF241    48
26     JFF312    20
27     JFF313    20
28     JFF316    48
29     JFF322    48
30     JFF327    36
31     JFF328    36
32     JFF331    36
33     JFF414    60
34     JFF416    48
35     JFF417    36
36     JKP102    52
37     JKP104    56
38     JKP110    77
39     JKP112    77
40     JKP202    54
41     JKP204    54
42     JKP210    78
43     JKP212    78

In [11]:
# as we just use a 100 sections from origional dataset, we try to manully choose available classroom to make the ratio of 
# of registed student and # of available seats similiar for origional and new subset data
course20153=course_enrollment.loc[course_enrollment.loc[:,"Term"]==20153,:]
course20153=course20153[(course20153.loc[:,"First End Time"]==course20153.loc[:,"First End Time"])|
                        (course20153.loc[:,"First Begin Time"]==course20153.loc[:,"First Begin Time"])]
course20153=course20153.loc[course20153.loc[:,"Reg Count"]<=149,:]


# calculate timelength for 20153
timelength=[]
for i in course20153.index:
    time1=course20153.loc[i,"First End Time"]
    time2=course20153.loc[i,"First Begin Time"]
    minutediff=((time1.hour*60+time1.minute)-(time2.hour*60+time2.minute)+10)
    halfhour=minutediff/30
    if minutediff%30>0:
        halfhour+=1
    timelength.append(halfhour)
course20153.loc[:,"timelength"]=timelength


# origional ratio of registered student and number of seats
print float(sum(course20153["Reg Count"]))/(sum(capacity1["Size"]))
print float(sum(course20153["timelength"]))
print (len(capacity1)*7*28)
ratio_origional=float(sum(course20153.loc[i,"Reg Count"]*course20153.loc[i,"timelength"] for i in course20153.index))/(sum(capacity1["Size"])*7*28)
ratio1=float(sum(course20153["Reg Count"]))/(sum(capacity1["Size"]))
print "\n"
print "add time "+str(ratio_origional)
print "no time "+str(ratio1)
# manully choose classroom to make the new ratio is similiar to the origional ratio
capacity=pd.DataFrame({"Room":["JFF LL105","ACC310","BRI202","JKP102","JFF236",
                               "JKP110","ACC201","ACC312","BRI5","JFF414","ACC303",
                               "JFF LL102","JKP202","JFF416","JFF LL103","JKP204","JFF233","JKP112","JKP212","JKP210"],
                       "Size":[149,54,42,52,60,77,48,20,42,60,46,48,54,48,48,54,60,77,78,78]})#,"BRI203","BRI204",42,42,"JKP202","JKP104",,54,56
print sum(section_info["Reg Count"])/sum(capacity["Size"])
print sum(section_info["timelength"])
print (len(capacity)*5*27)
ratio_new=sum(section_info.loc[i,"Reg Count"]*section_info.loc[i,"timelength"] for i in section_info.index)/(sum(capacity["Size"])*5*27)
ratio2=sum(section_info["Reg Count"])/sum(capacity["Size"])
print "\n"
print "add time "+str(ratio_new)
print "no time "+str(ratio2)

9.69407894737
2816.0
8624


add time 0.23989871442
no time 9.69407894737
3.15564853556
373
2700


add time 0.08794049279404928
no time 3.15564853556

In [12]:
section_info.to_excel("section_info.xlsx")
capacity.to_excel("selected_capacity.xlsx")

In [51]:
print section_info.loc[range(50),"Reg Count"]
print section_info.loc[range(50,100),"Reg Count"]

0     34.0
1     44.0
2     17.0
3     26.0
4     33.0
5     31.0
6     35.0
7     19.0
8     26.0
9     14.0
10    34.0
11    39.0
12    18.0
13    40.0
14    42.0
15    25.0
16    49.0
17    36.0
18    49.0
19    27.0
20    34.0
21    22.0
22    37.0
23    64.0
24    30.0
25    37.0
26    10.0
27    54.0
28    38.0
29    73.0
30    53.0
31    27.0
32    39.0
33    39.0
34     7.0
35    35.0
36    18.0
37    30.0
38    45.0
39    38.0
40    20.0
41     4.0
42    45.0
43    34.0
44    35.0
45    73.0
46    39.0
47    72.0
48    74.0
49    34.0
Name: Reg Count, dtype: float64
50     68.0
51     36.0
52     53.0
53     33.0
54     33.0
55     29.0
56     19.0
57     30.0
58     16.0
59     39.0
60     34.0
61     63.0
62     21.0
63     47.0
64     61.0
65     63.0
66     37.0
67     15.0
68      8.0
69     33.0
70     21.0
71     33.0
72     30.0
73     45.0
74     34.0
75     33.0
76     31.0
77    117.0
78     38.0
79     25.0
80     82.0
81      7.0
82     50.0
83     42.0
84     41.0
85     10.0
86     31.0
87     71.0
88     28.0
89     40.0
90     19.0
91     42.0
92     28.0
93     96.0
94     27.0
95     41.0
96     74.0
97     33.0
98     34.0
99     32.0
Name: Reg Count, dtype: float64

In [52]:
#print mean(section100.loc[:,"Reg Count"])
print max(section_info.loc[:,"Reg Count"])
print min(section_info.loc[:,"Reg Count"])

117.0
4.0

## Build variables

In [53]:
# What we need to extract from data
# prediction about student registeration for every section
# how many section we need to schedule
# the pattern, time length of each section
# classroom capacity

# Variables
# course name
C={}
index=0
for i in section_info["section"]:
    C[i]=section_info.loc[section_info.loc[:,"section"]==i,"course"].get(index)
    index+=1
# section of course
I=section_info["section"]
# classroom
J=capacity["Room"]
# pattern of session (less than catagories in origional dataset)
P=["Monday","Tuesday","Wednesday","Thursday","Friday"]
P=pd.Series(i for i in P)
# start time of session (from 8:00am to 9:00pm,so the real classtime is between 8:00am to 10:00pm)
T1={}
time = datetime.timedelta(hours=8,minutes=0, seconds=0)
for i in range(27):
    T1[str(time+timedelta(hours=0.5*i))]=i
T=pd.Series(i for i in range(27))

# seat
seat={}
for index,row in capacity.iterrows():
    seat[row["Room"]]=row["Size"]
#seat=pd.Series(i for i in seat)
    
# pattern of each section
PS={}
index=0
for i in I:
    PS[i]=section_info.loc[section_info.loc[:,"section"]==i,"pattern"].get(index)
    #print i,PS[i]
    index+=1
#PS=pd.Series(i for i in PS)
    
#print "/n/n"
# timelength of each section
TS={}
index=0
for i in I:
    TS[i]=section_info.loc[section_info.loc[:,"section"]==i,"timelength"].get(index)
    #print i,TS[i]
    index+=1
#TS=pd.Series(i for i in TS)

#define primetime
primetime=range(4,21)

## Build Model

In [55]:
# Building model
mod=grb.Model()

## Decision Variables

In [56]:
X={}
for i in I: # section id
    for j in J: # classroom
        for p in P: # day of week
             for t in T: # start timeslot of sesstion
                    X[i,j,p,t]=mod.addVar(vtype=grb.GRB.BINARY, name='x[{0},{1},{2},{3}]'.format(i,j,p,t))

                    
# add one more variable PD[f,p,b], f is faculty(professor), p is day of week, b is the building
# PD[f,p,b]=1 means that prof f in p day has class in building b 
PD={}
Building=["ACC","BRI","HOH","JFF","JKP"]
for f in Prof:
    for p in P:
        for b in Building:
            PD[f,p,b]=mod.addVar(vtype=grb.GRB.BINARY,name='PD[{0},{1},{2}]'.format(f,p,b))

# add one more numeric variable Dp,f means that professor f have to show up in campus in p day of week
D={}
for f in Prof:
    for p in P:
        D[p,f]=mod.addVar(vtype=grb.GRB.BINARY,name='x[{0}]'.format(p))

#add one more varible PTi. PTi means that how many sessions of section i are in prime time
PT={}
for i in I:
    PT[i]=mod.addVar(vtype=grb.GRB.INTEGER,name='PT[{0}]'.format(i))

## Objective

In [57]:
# Objective
# As i set the constraint1 below, so the section with 2 or 3 sessions will have higher weight here
# but if i do not set constraint1, we cannot promise other sections will not take the vacancy
# for example, if DSO570 assigned to M/W 12:00, namely X[DSO570,j,"MW",12:00]=1, but X[i,j,"M",12:00]=0 and X[i,j,"W",12:00]=0, 
# so other courses maight be assign to this time too
mod.setObjective((
    # classroom utilization (max)
    sum(X[i,j,p,t]*student[i]/seat[j] for i in I for j in J for p in P for t in T)/numofsections
    # number of days that professor has class (min)
    -sum(D[p,f] for f in Prof for p in P)/numofprof
    # number of buildings that professor need to go in anyday that he has class (min)
    -sum(PD[f,p,b] for f in Prof for p in P for b in Building)/numofprof
    # prime time utilization (max)
    +sum(PT[i] for i in I)/numofsections
),sense=grb.GRB.MAXIMIZE)

## Constraints

In [58]:
# constraints
I_twoday=pd.Series()
I_oneday=pd.Series()
for i in I:
    if PS.get(i)==1:
        I_oneday=I_oneday.append(pd.Series(i))
    else:
        I_twoday=I_twoday.append(pd.Series(i))

In [59]:
# constraint1
# in each time slot in each day every professor can only teach one session at the same time
constraint1={}
for t in T:
    for p in P:
        for prof in Prof:
            constraint1[t,p,prof]=mod.addConstr(sum(X[i,j,p,t] for i in professor[prof].values for j in J)<=1)

In [60]:
# new constraint2
# every timeslot in every classroom in a specific day, there will be only one or zero class
constraint2={}
for j in J:
    for t in T:
        for p in P:
            constraint2[j,t,p]=mod.addConstr(sum(X[i,j,p,t] for i in I)<=1)
            
# in the next (number of required sessions)*2 timeslot all of X should be 0
I2=I
for i1 in I:
    I2=I2.drop(pd.Index(I).get_loc(i1))#pd.Index(I).get_loc(i1)
    for j in J:
        for t in T:
            for p in P:
                timeslots=int(TS[i1])
                if t<=(27-timeslots): # avoid a situation that three hours course is assigned to 8:00 pm
                    #print i1,j,p,t
                    constraint2[i1,j,t,p]=mod.addConstr((X[i1,j,p,t]+sum(X[i2,j,p,t+num] for i2 in I2 for num in range(0,timeslots)))<=1,name="")

In [61]:
# this constraint3 is only for those sections whose pattern is 2, which means they have two session every week.
constraint3={}
for i in I_twoday:
    for j in J:
        for t in T:
            constraint3[i,j,"M",t]=mod.addConstr(X[i,j,"Wednesday",t]== X[i,j,"Monday",t],name="") 
            # the section with two sessions must have same 0/1 in M and W
            
            constraint3[i,j,"T",t]=mod.addConstr(X[i,j,"Thursday",t] == X[i,j,"Tuesday",t],name="") 
            # the section with two sessions must have same 0/1 in M and W

In [62]:
# this constraint4 is to control that when we maximum the utilization rate,the number of student registered 
#for one section should less than the classroom capacity
constraint4={}
for i in I:
    for j in J:
        for p in P:
             for t in T:
                    constraint4[i,j,p,t]=mod.addConstr(X[i,j,p,t]*student[i]<=seat[j],name="")

In [63]:
# this constraint5 is to make sure that in all time in all classroom in all day, 
#for each section, sum(X)=required sessions
constraint5={}
for i in I:
    constraint5[i]=mod.addConstr(sum(X[i,j,p,t] for j in J for p in P for t in T)==PS.get(i),name="")

In [64]:
#constraint6: No Friday class for MW and TH section
constraint6={}
for i in I_twoday:
    constraint6[i] = mod.addConstr(sum(X[i,j,"Friday",t] for j in J for t in T) == 0)

In [65]:
#constraint7:no class can last longer than the '9PM-9.30PM' block
constraint7={}
for i in I:
    constraint7[i] = mod.addConstr(sum(X[i,j,p,T.max()-ts] for j in J for p in P for ts in range(int(TS[i]))) == 0)

In [66]:
# building to classroom
ACC=[]
BRI=[]
HOH=[]
JFF=[]
JKP=[]
for j in J:
    if j[0:3]=="ACC":
        ACC.append(j)
    elif j[0:3]=="BRI":
        BRI.append(j)
    elif j[0:3]=="HOH":
        HOH.append(j)
    elif j[0:3]=="JFF":
        JFF.append(j)
    elif j[0:3]=="JKP":
        JKP.append(j)
BtoC={"ACC":ACC,"BRI":BRI,"HOH":HOH,"JFF":JFF,"JKP":JKP}

In [67]:
# constraint8 for each professor, make them teach in same building for everyday they teach
constraint8={}

for f in Prof:
    for p in P:
        for b in Building:
            courses=professor.get(f)
            classrooms=BtoC.get(b)
            for i in courses:
                for j in classrooms:
                    for t in T:
                        constraint8[f,p,b,i,j,t]=mod.addConstr(PD[f,p,b]>=X[i,j,p,t])
                        
for f in Prof:
    for p in P:
        mod.addConstr(sum(PD[f,p,b] for b in Building)<=1)

In [68]:
# constraint9 is to minimum the day that professor show in campus
constraint9={}

for f in Prof:
    for p in P:
        for i in professor.get(f):
            constraint9[f,p,i]=mod.addConstr(sum(X[i,j,p,t] for j in J for t in T)<=D[p,f])

In [69]:
#constraint10 is to maximum the prime time of classrooms used by the course schedule
constraint10={}
for i in I:
    #print i
    constraint10[i]=mod.addConstr(sum(X[i,j,p,t] for j in J for p in P for t in primetime if(t+TS[i])<=20)>=PT[i])

In [70]:
print "number of constrints "+str(len(constraint10)+len(constraint9)+len(constraint8)+len(constraint7)+len(constraint6)+len(constraint5)+len(constraint4)+len(constraint3)+len(constraint2)+len(constraint1))

number of constrints 871860

## Best solution output

In [71]:
mod.setParam("TimeLimit",6000)
mod.optimize()
mod.setParam('OutputFlag',False)

print('Optimal solution:',mod.ObjVal)

Changed value of parameter TimeLimit to 6000.0
   Prev: 1e+100  Min: 0.0  Max: 1e+100  Default: 1e+100
Optimize a model with 872230 rows, 272320 columns and 47237950 nonzeros
Variable types: 0 continuous, 272320 integer (272220 binary)
Coefficient statistics:
  Matrix range     [1e+00, 2e+02]
  Objective range  [4e-04, 5e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Presolve removed 0 rows and 0 columns (presolve time = 5s) ...
Presolve removed 209895 rows and 370 columns
Presolve time: 8.47s

Explored 0 nodes (0 simplex iterations) in 28.79 seconds
Thread count was 1 (of 4 available processors)

Solution count 0

Model is infeasible or unbounded
Best objective -, best bound -, gap -

AttributeError: Unable to retrieve attribute 'ObjVal'

In [ ]:
# get the small subset of J that have classes in this classroom
J1=[]
for j in J:
    if sum(X[i,j,p,t].x for i in I for p in P for t in T)>0:
        J1.append(j)
#print J1

In [ ]:
# return a blank table
def blanktable():
    T1=[]
    blank=[]
    time = datetime.timedelta(hours=8,minutes=0, seconds=0)
    for i in range(27):
        T1.append(str(time+timedelta(hours=0.5*i)))
        blank.append("")
    schedule=pd.DataFrame({"# timeslot": range(27),
                           "timeslot":T1,
                           "Monday":blank,
                           "Tuesday":blank,
                           "Wednesday":blank,
                           "Thursday":blank,
                           "Friday":blank})
    sched_cols = ['# timeslot','timeslot','Monday','Tuesday','Wednesday','Thursday','Friday']
    schedule = schedule[sched_cols]
    schedule=schedule.set_index('# timeslot')
    return schedule

In [420]:
# put the optimal solution into our beautiful schedule table
timetable={}
for j in J1:
    #print "J is "+j
    #print "schedule"+j
    schedule1=blanktable()
    for i in I:
        for p in P:
            for t in T:
                if X[i,j,p,t].x>0:
                    for a in range(int(TS[i])):
                        schedule1.loc[t+a,p]=C[i]+" / "+str(i)
                        #print schedule1
    timetable["schedule"+j]=schedule1
    #print "timetable "+"schedule"+j
    #print timetable["schedule"+j]

In [421]:
output=pd.ExcelWriter("schedule_test.xlsx")
for j in J:
    if sum(X[i,j,p,t].x for i in I for p in P for t in T)>0:
        timetable["schedule"+j].to_excel(output,sheet_name=j,index=False)
output.save()

In [537]:
result=pd.DataFrame(columns=["I section","J classroom","P day of week","T time slots"])
num=0
for i in I:
    for j in J:
        for t in T:
            for p in P:
                result.loc[num,"I section"]=i
                result.loc[num,"J classroom"]=j
                result.loc[num,"P day of week"]=p
                result.loc[num,"T time slots"]=t
                num+=1
result.to_excel("saveX_new_ratio.xlsx")

In [270]:
# make sure that every professor is assigned to one building in the day that they have class
# constraint8
for f in Prof:
    for p in P:
        for b in Building:
            if PD[f,p,b].x>0:
                print f+" "+p+" "+b+" "+str(PD[f,p,b].x)

Erbstoesser, Eugene Tuesday ACC 1.0
Erbstoesser, Eugene Thursday ACC 1.0
Bristow, Duke Monday BRI 1.0
Bristow, Duke Wednesday BRI 1.0
Swartz, Mick Tuesday JKP 1.0
Swartz, Mick Thursday JKP 1.0
Lin, Thomas, W Monday JKP 1.0
Lin, Thomas, W Wednesday JKP 1.0
Tully, Stephanie Tuesday BRI 1.0
Tully, Stephanie Thursday BRI 1.0
Kalb, Ira, S Friday BRI 1.0
Ferguson, Trudi, C Tuesday JKP 1.0
Ferguson, Trudi, C Thursday JKP 1.0
Levi, Yaron Tuesday JKP 1.0
Levi, Yaron Thursday JKP 1.0
Layton, Rose, M Tuesday BRI 1.0
Layton, Rose, M Thursday BRI 1.0
Ozbas, Oguzhan Monday JKP 1.0
Ozbas, Oguzhan Wednesday JKP 1.0
Bemis, Nimfa, Abarquez Tuesday JFF 1.0
Bemis, Nimfa, Abarquez Thursday JFF 1.0
Moyer, Stephen Monday JKP 1.0
Moyer, Stephen Wednesday JKP 1.0
Hopkins, Merle, W Monday ACC 1.0
Hopkins, Merle, W Wednesday ACC 1.0
Hopkins, Merle, W Friday JFF 1.0
Bayiz, Murat Tuesday ACC 1.0
Bayiz, Murat Thursday ACC 1.0
Randhawa, Smrity, P Tuesday JFF 1.0
Randhawa, Smrity, P Thursday JFF 1.0
Wakslak, Cheryl, Jan Monday ACC 1.0
Wakslak, Cheryl, Jan Wednesday ACC 1.0
Hankins, Gary, W Monday BRI 1.0
Hankins, Gary, W Wednesday BRI 1.0
Rogers, Philip Friday ACC 1.0
Tellis, Gerard, J Tuesday ACC 1.0
Tellis, Gerard, J Thursday ACC 1.0
Bresnahan, Chris Friday JKP 1.0
Davila, Ruben, Allen Monday BRI 1.0
Davila, Ruben, Allen Wednesday BRI 1.0
Coombs, Michael, Wallace Friday JFF 1.0
Markwardt, Daylanne Monday JFF 1.0
Markwardt, Daylanne Wednesday JFF 1.0
Patterson, Kelly, Lee Friday JKP 1.0
Perner, Lars, Erik Friday BRI 1.0
Allen, Eric Monday JFF 1.0
Allen, Eric Wednesday JFF 1.0
Tinseth, Andrew Monday JFF 1.0
Tinseth, Andrew Wednesday JFF 1.0
Durguner, Seda Tuesday JKP 1.0
Durguner, Seda Thursday JKP 1.0
Karuna, Christo Monday BRI 1.0
Karuna, Christo Wednesday BRI 1.0
Bridges, Bob Monday ACC 1.0
Bridges, Bob Wednesday ACC 1.0
Javanmard, Adel Friday JKP 1.0
Phiroz, Zal Tuesday JFF 1.0
Phiroz, Zal Thursday JFF 1.0
Nikkhoo, Ivan, K Friday JFF 1.0
Schorr, Dennis Tuesday JFF 1.0
Schorr, Dennis Thursday JFF 1.0
Murr, Andrew, David Monday JFF 1.0
Murr, Andrew, David Wednesday JFF 1.0
Bonner, Sarah, Elizabeth Monday ACC 1.0
Bonner, Sarah, Elizabeth Wednesday ACC 1.0
Pasztor, Sabrina Tuesday ACC 1.0
Pasztor, Sabrina Thursday ACC 1.0
El Haddad, Christine Monday JKP 1.0
El Haddad, Christine Wednesday JKP 1.0
Coker, Noble Tuesday JKP 1.0
Coker, Noble Thursday JKP 1.0
Wiltermuth, Scott, Steven Monday JKP 1.0
Wiltermuth, Scott, Steven Wednesday JKP 1.0
Summerlin, Michael Friday ACC 1.0
Plotts, Julia, Gardner Monday JKP 1.0
Plotts, Julia, Gardner Wednesday JKP 1.0
Ochiumi, Hiroshi Tuesday ACC 1.0
Ochiumi, Hiroshi Thursday ACC 1.0
Miller, Justin Monday JFF 1.0
Miller, Justin Wednesday JFF 1.0
Levitin, Lloyd, Alan Monday JKP 1.0
Levitin, Lloyd, Alan Wednesday JKP 1.0
Owens, James Monday JFF 1.0
Owens, James Wednesday JFF 1.0
Cerling, Lee Monday JFF 1.0
Cerling, Lee Wednesday JFF 1.0
Little, Sharoni Tuesday JFF 1.0
Little, Sharoni Thursday JFF 1.0
Wilson Sweeney, Zivia, L Monday JKP 1.0
Wilson Sweeney, Zivia, L Wednesday JKP 1.0
Majchrzak, Ann Monday ACC 1.0
Majchrzak, Ann Wednesday ACC 1.0
Tolan, Johanna, Brockelman Friday JKP 1.0
Soliman, Mark Friday JFF 1.0
Kovacevich, Rex, Alan Friday BRI 1.0
Sharif, Abbass Friday JFF 1.0
Farzan, Azin Monday JFF 1.0
Farzan, Azin Wednesday JFF 1.0
Colman, Maria Tuesday ACC 1.0
Colman, Maria Thursday ACC 1.0
Ahern, Kenneth Tuesday JKP 1.0
Ahern, Kenneth Thursday JKP 1.0
Wolfe, Terance, J Tuesday JFF 1.0
Wolfe, Terance, J Thursday JFF 1.0
Swenson, Charles, W Tuesday JKP 1.0
Swenson, Charles, W Thursday JKP 1.0
Srinivasan, Ashok Monday JFF 1.0
Srinivasan, Ashok Wednesday JFF 1.0
Smith, Lori, L Tuesday ACC 1.0
Smith, Lori, L Thursday ACC 1.0
Freed, Chrislynn Tuesday BRI 1.0
Freed, Chrislynn Thursday BRI 1.0
Burgos, Miriam, T Tuesday JKP 1.0
Burgos, Miriam, T Thursday JKP 1.0
Pereira, Francis Monday JFF 1.0
Pereira, Francis Wednesday JFF 1.0
Durguner, Sena Friday JFF 1.0
Voigt, Carl, W Monday BRI 1.0
Voigt, Carl, W Wednesday BRI 1.0
Gupta, Vishal Friday JFF 1.0
Wong, Janna, Robin Tuesday JFF 1.0
Wong, Janna, Robin Thursday JFF 1.0
Shook, Douglas Tuesday JKP 1.0
Shook, Douglas Thursday JKP 1.0
Folkes, Valerie, S Monday ACC 1.0
Folkes, Valerie, S Wednesday ACC 1.0
Abrams, Scott Monday JKP 1.0
Abrams, Scott Wednesday JKP 1.0

In [271]:
# check every professor's class day
# constraint9
for f in Prof:
    for p in P:
        if D[p,f].x>0:
            print f+" "+p+" "+str(D[p,f].x)

Erbstoesser, Eugene Tuesday 1.0
Erbstoesser, Eugene Thursday 1.0
Bristow, Duke Monday 1.0
Bristow, Duke Wednesday 1.0
Swartz, Mick Tuesday 1.0
Swartz, Mick Thursday 1.0
Lin, Thomas, W Monday 1.0
Lin, Thomas, W Wednesday 1.0
Tully, Stephanie Tuesday 1.0
Tully, Stephanie Thursday 1.0
Kalb, Ira, S Friday 1.0
Ferguson, Trudi, C Tuesday 1.0
Ferguson, Trudi, C Thursday 1.0
Levi, Yaron Tuesday 1.0
Levi, Yaron Thursday 1.0
Layton, Rose, M Tuesday 1.0
Layton, Rose, M Thursday 1.0
Ozbas, Oguzhan Monday 1.0
Ozbas, Oguzhan Wednesday 1.0
Bemis, Nimfa, Abarquez Tuesday 1.0
Bemis, Nimfa, Abarquez Thursday 1.0
Moyer, Stephen Monday 1.0
Moyer, Stephen Wednesday 1.0
Hopkins, Merle, W Monday 1.0
Hopkins, Merle, W Wednesday 1.0
Hopkins, Merle, W Friday 1.0
Bayiz, Murat Tuesday 1.0
Bayiz, Murat Thursday 1.0
Randhawa, Smrity, P Tuesday 1.0
Randhawa, Smrity, P Thursday 1.0
Wakslak, Cheryl, Jan Monday 1.0
Wakslak, Cheryl, Jan Wednesday 1.0
Hankins, Gary, W Monday 1.0
Hankins, Gary, W Wednesday 1.0
Rogers, Philip Friday 1.0
Tellis, Gerard, J Tuesday 1.0
Tellis, Gerard, J Thursday 1.0
Bresnahan, Chris Friday 1.0
Davila, Ruben, Allen Monday 1.0
Davila, Ruben, Allen Wednesday 1.0
Coombs, Michael, Wallace Friday 1.0
Markwardt, Daylanne Monday 1.0
Markwardt, Daylanne Wednesday 1.0
Patterson, Kelly, Lee Friday 1.0
Perner, Lars, Erik Friday 1.0
Allen, Eric Monday 1.0
Allen, Eric Wednesday 1.0
Tinseth, Andrew Monday 1.0
Tinseth, Andrew Wednesday 1.0
Durguner, Seda Tuesday 1.0
Durguner, Seda Thursday 1.0
Karuna, Christo Monday 1.0
Karuna, Christo Wednesday 1.0
Bridges, Bob Monday 1.0
Bridges, Bob Wednesday 1.0
Javanmard, Adel Friday 1.0
Phiroz, Zal Tuesday 1.0
Phiroz, Zal Thursday 1.0
Nikkhoo, Ivan, K Friday 1.0
Schorr, Dennis Tuesday 1.0
Schorr, Dennis Thursday 1.0
Murr, Andrew, David Monday 1.0
Murr, Andrew, David Wednesday 1.0
Bonner, Sarah, Elizabeth Monday 1.0
Bonner, Sarah, Elizabeth Wednesday 1.0
Pasztor, Sabrina Tuesday 1.0
Pasztor, Sabrina Thursday 1.0
El Haddad, Christine Monday 1.0
El Haddad, Christine Wednesday 1.0
Coker, Noble Tuesday 1.0
Coker, Noble Thursday 1.0
Wiltermuth, Scott, Steven Monday 1.0
Wiltermuth, Scott, Steven Wednesday 1.0
Summerlin, Michael Friday 1.0
Plotts, Julia, Gardner Monday 1.0
Plotts, Julia, Gardner Wednesday 1.0
Ochiumi, Hiroshi Tuesday 1.0
Ochiumi, Hiroshi Thursday 1.0
Miller, Justin Monday 1.0
Miller, Justin Wednesday 1.0
Levitin, Lloyd, Alan Monday 1.0
Levitin, Lloyd, Alan Wednesday 1.0
Owens, James Monday 1.0
Owens, James Wednesday 1.0
Cerling, Lee Monday 1.0
Cerling, Lee Wednesday 1.0
Little, Sharoni Tuesday 1.0
Little, Sharoni Thursday 1.0
Wilson Sweeney, Zivia, L Monday 1.0
Wilson Sweeney, Zivia, L Wednesday 1.0
Majchrzak, Ann Monday 1.0
Majchrzak, Ann Wednesday 1.0
Tolan, Johanna, Brockelman Friday 1.0
Soliman, Mark Friday 1.0
Kovacevich, Rex, Alan Friday 1.0
Sharif, Abbass Friday 1.0
Farzan, Azin Monday 1.0
Farzan, Azin Wednesday 1.0
Colman, Maria Tuesday 1.0
Colman, Maria Thursday 1.0
Ahern, Kenneth Tuesday 1.0
Ahern, Kenneth Thursday 1.0
Wolfe, Terance, J Tuesday 1.0
Wolfe, Terance, J Thursday 1.0
Swenson, Charles, W Tuesday 1.0
Swenson, Charles, W Thursday 1.0
Srinivasan, Ashok Monday 1.0
Srinivasan, Ashok Wednesday 1.0
Smith, Lori, L Tuesday 1.0
Smith, Lori, L Thursday 1.0
Freed, Chrislynn Tuesday 1.0
Freed, Chrislynn Thursday 1.0
Burgos, Miriam, T Tuesday 1.0
Burgos, Miriam, T Thursday 1.0
Pereira, Francis Monday 1.0
Pereira, Francis Wednesday 1.0
Durguner, Sena Friday 1.0
Voigt, Carl, W Monday 1.0
Voigt, Carl, W Wednesday 1.0
Gupta, Vishal Friday 1.0
Wong, Janna, Robin Tuesday 1.0
Wong, Janna, Robin Thursday 1.0
Shook, Douglas Tuesday 1.0
Shook, Douglas Thursday 1.0
Folkes, Valerie, S Monday 1.0
Folkes, Valerie, S Wednesday 1.0
Abrams, Scott Monday 1.0
Abrams, Scott Wednesday 1.0

In [272]:
# check the number of sessions in prime time of every section
# constraint10
for i in I:
    print str(i)+" "+str(PT[i].x)

14260 2.0
15904 0.0
15370 2.0
14532 2.0
14847 0.0
14816 1.0
15106 2.0
15406 2.0
14136 0.0
14056 2.0
15659 0.0
14790 2.0
15328 2.0
14029 1.0
14785 2.0
16236 2.0
14517 2.0
16667 2.0
16476 2.0
14055 2.0
14057 2.0
14893 1.0
16526 2.0
14736 1.0
14510 2.0
14738 1.0
66746 0.0
14519 2.0
14723 1.0
14832 1.0
14518 2.0
14508 2.0
14511 0.0
14789 0.0
14543 0.0
14052 2.0
15380 0.0
14915 1.0
14907 2.0
14398 1.0
16549 2.0
66742 2.0
14207 0.0
14689 0.0
15097 2.0
15098 0.0
15749 0.0
14725 0.0
15324 2.0
14978 2.0
14643 2.0
14913 1.0
15400 2.0
66785 2.0
14784 0.0
66769 2.0
66767 0.0
14515 0.0
16225 2.0
14734 1.0
14301 1.0
14810 1.0
15057 1.0
14909 0.0
14701 0.0
14724 1.0
66761 2.0
15094 2.0
14786 2.0
14731 1.0
16700 0.0
66751 2.0
14062 0.0
14901 2.0
15660 2.0
14814 1.0
14743 1.0
14294 2.0
14772 2.0
15560 0.0
15053 1.0
14782 2.0
16234 0.0
14487 1.0
14765 2.0
15372 0.0
16692 0.0
14748 1.0
16678 0.0
14791 2.0
15362 0.0
14025 2.0
15064 1.0
66773 2.0
16228 2.0
16508 2.0
15656 2.0
14726 1.0
14783 2.0
14754 1.0